App\Entity\Product:
  proprerties:
    name: 
      - NotBlank: {message: "Le nom du produit est obligatoire"}
      - Lenght: {min: 3, max: 255, minMessage: "Le nom du produit doit faire plus de 3 caractères"}
    price:
      - NotBlank: {message: "Le prix du produit est obligatoire"}